version: '3.6'

services:
  recruitment-app:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    user: "${USER_ID:-1000}:${USER_ID:-1000}"
    ports:
      - 3160:3160
